name: foodball_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.4.0"

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  dio: ^5.9.0
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # FIX: sesuai Dart 3.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/football/
